default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5 
  username: postgres
  password: Waithira2013

development:
  <<: *default
  database: Budget_App_development

test:
  <<: *default
  database: Budget_App_test

production:
  <<: *default
  database: Budget_App_production
  username: Budget_App
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>
